### ISSUE TITLE
Add details for Hacktoberfest contributions via "Advocacy"

### ISSUE THREAD

**Issue by laylark** [techlahoma/Hacktoberfest#6]
The goal of this issue is to inform and encourage Techlahoma members to contribute in a variety of low or non-code ways while participating in Hacktoberfest.

## Tasks

- Update `README.md`
- Create `/advocacy/.keep`

### Update `README.md`

Hacktoberfest is allowing low or non-code contributions which includes:

- Talks or presentations
- Technical blog posts
- Podcasts
- Case studies
- Social media

Please add to the `README.md`:
- The above information, **explicitly mentioning the contribution must be made during the month of October 2022**
- A link to https://hacktoberfest.com/about/#low-or-non-code
- A link to the `/advocacy` directory that will be created as a part of this issue
- Instructions for having people commit a new `your_contribution_title.yaml` file into the `/advocacy` directory with the following format:

```yaml
name: John Smith
title: Here is my talk/podcast/etc. post title.
url: https://example.com/my-dash-blog-post
date: 2022-10-31
description: Here is a brief description and any supplemental information for my talk/podcast/etc.
```

### Create `/advocacy/.keep`

You will need to create an empty `.keep` file in a new `/advocacy` directory as a part of this issue. You can do this in the CLI by:

```bash
mkdir advocacy
touch advocacy/.keep
```
